config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :lists, only: %i[index show new create] do
    resources :bookmarks, only: %i[new create]
  end
  resources :bookmarks, only: %i[destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bookmark.rb
class Bookmark < ApplicationRecord
  belongs_to :movie
  belongs_to :list
  validates :movie_id, presence: true, uniqueness: { scope: :list_id }
  validates :list_id, presence: true
  validates :comment, length: { minimum: 6 }, presence: true
end

app/models/list.rb
class List < ApplicationRecord
  has_many :bookmarks, dependent: :destroy
  has_many :movies, through: :bookmarks
  validates :name, uniqueness: true, presence: true
  has_one_attached :photo
end

app/models/movie.rb
class Movie < ApplicationRecord
  has_many :bookmarks
  validates :title, uniqueness: true, presence: true
  validates :overview, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookmarks_controller.rb
class BookmarksController < ApplicationController
  before_action :set_list, only: %i[new create]
  before_action :all_lists

  def new
    @bookmark = Bookmark.new
  end

  def create
    @bookmark = Bookmark.new(bookmark_params)
    @bookmark.list = @list
    # @bookmark.movie_id =
    if @bookmark.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @bookmark = Bookmark.find(params[:id])
    @bookmark.destroy
    redirect_to list_path(@bookmark.list), status: :see_other
  end

  private

  def bookmark_params
    params.require(:bookmark).permit(:comment, :movie_id)
  end

  def set_list
    @list = List.find(params[:list_id])
  end

  def all_lists
    @all_lists = List.all
  end
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_action :set_list, only: [:show]
  before_action :all_lists


  def index
    @lists = List.all
    new
  end

  def show
    @bookmarks = Bookmark.all
    @bookmark = Bookmark.new

    @img_url = @list.photo.key.nil? ? 'https://images.unsplash.com/photo-1485846234645-a62644f84728?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2059&q=80' : @list.photo.url
  end

  def new
    @list = List.new
  end

  def create
    @list = List.new(list_params)
    if @list.save
      redirect_to list_path(@list)
    else
      render :new, status: :unprocessable_entity
    end
  end

  private

  def all_lists
    @all_lists = List.all
  end

  def set_list
    @list = List.find(params[:id])
  end

  def list_params
    params.require(:list).permit(:name, :photo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookmarks_helper.rb
module BookmarksHelper
end

app/helpers/lists_helper.rb
module ListsHelper
end

app/views/bookmarks/_form.html.erb
<%= simple_form_for [list, @bookmark] do |f| %>
	<%= f.association :movie, collection: Movie.all.order(:title), prompt: "Choose a Movie" %>
  <%= f.input :comment %>
	<%= f.submit "Create", class: "btn btn-dark rounded-pill"%>
<% end %>

app/views/bookmarks/new.html.erb
<h1>New Bookmark</h1>

<%= render "form", list: @list, bookmark: @bookmark %>

<%= link_to "< back", list_path(@list), class: "btn btn-secondary rounded-pill mt-3" %>

app/views/layouts/_listnavbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container">
    <a class="navbar-brand" href="/lists">
      <img src="https://cdn-icons-png.flaticon.com/512/2824/2824496.png" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

          <li class="nav-item dropdown mx-3">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">All Lists</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/lists">All Lists</a></li>
              <li><hr class="dropdown-divider"></li>
              <% @all_lists.each do |list| %>
                <li><%= link_to list.name, list_path(list), class: "dropdown-item" %></li>
              <% end %>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#staticBackdropList">+ Add List</a>
          </li>
      </ul>
    </div>
  </div>
</div>

<!-- Modal -->
  <div class="modal fade" id="staticBackdropList" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog rounded">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Create new list</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "form", list: @list %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary rounded-pill" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/_movienavbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container">
    <a class="navbar-brand" href="/lists">
      <img src="https://cdn-icons-png.flaticon.com/512/2824/2824496.png" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

          <li class="nav-item dropdown mx-3">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">All Lists</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/lists">All Lists</a></li>
              <li><hr class="dropdown-divider"></li>
              <% @all_lists.each do |list| %>
                <li><%= link_to list.name, list_path(list), class: "dropdown-item" %></li>
              <% end %>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#staticBackdropMovie">+ Add Movie</a>
          </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
  <div class="container">
    <a class="navbar-brand" href="/lists">
      <img src="https://cdn-icons-png.flaticon.com/512/2824/2824496.png" />
</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">

          <li class="nav-item dropdown mx-3">
            <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">All Lists</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="/lists">All Lists</a></li>
              <li><hr class="dropdown-divider"></li>
              <% @all_lists.each do |list| %>
                <li><%= link_to list.name, list_path(list), class: "dropdown-item" %></li>
              <% end %>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link" href="#" data-bs-toggle="modal" data-bs-target="#staticBackdropList">+ Add List</a>
          </li>
      </ul>
    </div>
  </div>
</div>

<!-- Modal -->
  <div class="modal fade" id="staticBackdropList" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog rounded">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Create new list</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "form", list: @list %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary rounded-pill" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Brilliant Watchlist</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/lists/_form.html.erb
<%= simple_form_for(list) do |f| %>
	<%= f.input :name %>
  <%= f.input :photo, as: :file, label: 'Add a coverphoto for the list' %>
	<%= f.submit "Create", class: "btn btn-dark rounded-pill"%>
<% end %>

app/views/lists/index.html.erb
<%= render "layouts/listnavbar" %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)), url(https://images.unsplash.com/photo-1536440136628-849c177e76a1?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=1625&q=80);">
  <div class="container">
    <h1 class="my-3">Save any kind of movies!</h1>
    <p>Change your life with amazing movies!</p>
    <a class="btn btn-light rounded-pill mr-3" href="#content">Experience existing lists</a>
    <a class="btn btn-outline-light rounded-pill mx-2" href="#" data-bs-toggle="modal" data-bs-target="#staticBackdropList">+ Add List</a>
  </div>
</div>

<div id="content" class="container text-center my-3">
  <div class="row">
    <% @lists.each do |list| %>
      <div class="col-12 col-sm-6 col-lg-4 mb-3">
        <div class="card">
          <% if list.photo.key.nil? %>
            <img src="https://images.unsplash.com/photo-1485846234645-a62644f84728?ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D&auto=format&fit=crop&w=2059&q=80" class="card-img-top" alt="<%= list.name %>">
          <% else %>
            <%= cl_image_tag list.photo.key, height: 300, width: 400, crop: :fit, class: "card-img-top", alt: list.name %>
          <% end %>
          <div class="card-body">
            <h5 class="card-title"><%= list.name %></h5>
            <%= link_to "View List", list_path(list), class: "btn btn-outline-dark rounded-pill" %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex my-3 justify-content-end">
    <button type="button" class="btn btn-outline-dark rounded-pill" data-bs-toggle="modal" data-bs-target="#staticBackdropList">+ Add a new List</button>
  </div>
</div>

app/views/lists/new.html.erb
<h1>New List</h1>

<%= render "form", list: @list %>

app/views/lists/show.html.erb
<%= render "layouts/movienavbar" %>
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.7),rgba(0,0,0,0.7)), url(<%= @img_url %>);">
  <div class="container">
    <h1 class="my-3"><%= @list.name %></h1>
    <a class="btn btn-light rounded-pill mr-3" href="#content">Experience this list</a>
    <a class="btn btn-outline-light rounded-pill mx-2" href="#" data-bs-toggle="modal" data-bs-target="#staticBackdropMovie">+ Add movie</a>
  </div>
</div>
<div id="content" class="container my-3">
  <div class="row g-3 justify-content-space-evenly" style="gap: 5px;">
    <% @list.bookmarks.each do |bookmark| %>
      <div class="card overflow-hidden mb-3 px-0 col-12 col-lg-6">
        <div class="row g-0">
          <div class="col-md-5">
            <img src="<%= bookmark.movie.poster_url %>" class="img-fluid m-0" style="width: 100%" alt="<%= bookmark.movie.title %>">
          </div>
          <div class="col-md-7">
            <div class="card-body">
              <h5 class="card-title"><%= bookmark.movie.title %></h5>
              <p class="card-text"><%= bookmark.movie.overview %></p>
              <p class="card-text">"<%= bookmark.comment %>"</p>
              <p><%= link_to "DELETE", bookmark_path(bookmark), data: {turbo_method: :delete, turbo_confirm: "Are you sure?"}, class:"btn btn-outline-dark rounded-pill"%></p>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
  <div class="d-flex my-3 justify-content-between">
    <%= link_to "< back", lists_path, class: "btn btn-outline-secondary rounded-pill" %>
    <%= link_to "+ Add Movie", new_list_bookmark_path(@list), class: "btn btn-outline-secondary rounded-pill" %>
  </div>
</div>

<!-- Modal -->
  <div class="modal fade" id="staticBackdropMovie" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
    <div class="modal-dialog rounded">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="staticBackdropLabel">Add a Movie to "<%= @list.name %>"</h1>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <%= render "bookmarks/form", list: @list, bookmark: @bookmark %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-outline-secondary rounded-pill" data-bs-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>